# Generated by Django 3.1.7 on 2021-03-08 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_ingredients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='status',
            new_name='favourite',
        ),
    ]
