# Generated by Django 3.1.7 on 2021-03-10 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20210310_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='favourite',
        ),
        migrations.DeleteModel(
            name='FavouriteRecipe',
        ),
    ]
